### ISSUE TITLE
Problem with adding new files some randomly fail when add to user playlist

### ISSUE THREAD

**Issue by ijabz** [hendriks73/obstmusic#1]
Hi, I have a test of adding an album to Music app, the files are added individually and some usually fail, but it is random which fail and I have enabled the debugging and if i paste the  applescript code into Applescript it works. The files are quite large (wav files) and so Im assuming that maybe there is some kind of timing issue, is the add method synchronous 

            Application app = Application.getInstance();
            JaplScriptFile [] musicFiles = { new JaplScriptFile(Paths.get(filename)) };
            Track track = app.add(musicFiles, userPlaylist);
            if(track!=null && track.isInstanceOf(FileTrack.CLASS))
            {
                FileTrack fileTrack = track.cast(FileTrack.class);
                //For Wav
                updateITunesLibTrackFromSong(fileTrack, song);
            }

What Im finding is the songs are actually added to Music app, but sometimes not added to my userPlaylist, user Playlist reference is kept between tell calls is that wrong have I got to retrieve it in one music app session for it to work reliably.

**Comment by hendriks73** [comment]
How does this fail? Is there an error message?

> user Playlist reference is kept between tell calls is that wrong have I got to retrieve it in one music app session for it to work reliably.

References are stateless/sessionless. I.e. you can re-use them in different sessions. So that should not be an issue.

**Comment by ijabz** [comment]
Had a few different errors but the most common error is

    NSAppleScriptErrorAppName = Music;
    NSAppleScriptErrorBriefMessage = "Can’t get class of file track id 11128 of user playlist id 11079 of source id 64.";
    NSAppleScriptErrorMessage = "Music got an error: Can’t get class of file track id 11128 of user playlist id 11079 of source id 64.";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {33, 5}";
}


05/04/2022 15.06.53:BST:FINE: Resetting session for thread ITunesUpdate:1
05/04/2022 15.06.53:BST:FINE: Starting new session for thread ITunesUpdate:1
05/04/2022 15.06.53:BST:FINE: Adding fragment to session for thread Thread[ITunesUpdate:1,10,Song Kong Thread Group]: "tell application "Music"
  add  {(POSIX file ("/Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/05 - Breathe In Breathe Out.wav"))} to «class cUsP» id 11079 of «class cSrc» id 64 
end tell
"
05/04/2022 15.06.53:BST:FINE: Script: tell application "Music"
  add  {(POSIX file ("/Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/05 - Breathe In Breathe Out.wav"))} to «class cUsP» id 11079 of «class cSrc» id 64 
end tell


05/04/2022 15.06.53:BST:FINE: Return value: «class cFlT» id 11128 of «class cUsP» id 11079 of «class cSrc» id 64
05/04/2022 15.06.53:BST:FINE: Resetting session for thread ITunesUpdate:1
05/04/2022 15.06.53:BST:FINE: Committing session for thread ITunesUpdate:1
05/04/2022 15.06.53:BST:FINE: Committing empty session.
05/04/2022 15.06.53:BST:FINE: Script: tell application "Music"
return class of «class cFlT» id 11128 of «class cUsP» id 11079 of «class cSrc» id 64
end tell

05/04/2022 15.06.53:BST:Errors:addError:SEVERE: Adding Error:Unable to add new track /Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/05 - Breathe In Breathe Out.wav to Music app because {
    NSAppleScriptErrorAppName = Music;
    NSAppleScriptErrorBriefMessage = "Can’t get class of file track id 11128 of user playlist id 11079 of source id 64.";
    NSAppleScriptErrorMessage = "Music got an error: Can’t get class of file track id 11128 of user playlist id 11079 of source id 64.";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {33, 5}";
}
java.lang.Exception
	at com.jthink.songkong.analyse.general.Errors.addError(Errors.java:28)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.addNewTrack(OSXUpdateMusicWithChanges.java:331)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.analyseFiles(OSXUpdateMusicWithChanges.java:173)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.updateItunes(OSXUpdateMusicWithChanges.java:217)
	at com.jthink.songkong.ituneshelper.UpdateItunesWithChanges.call(UpdateItunesWithChanges.java:156)
	at com.jthink.songkong.ituneshelper.UpdateItunesWithChanges.call(UpdateItunesWithChanges.java:33)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ijabz** [comment]
And sometimes there is no error as such but 

`app.add(musicFiles, userPlaylist);`

returns null so Track is null, the file is added to Music app, but not added to userPlaylist

**Comment by hendriks73** [comment]
The stacktrace you posted hints that you have been using JaplScript sessions, but they are not in the code you have posted.

Did you perhaps use sessions somewhere else that you didn't `commit()`?

I highly recommend to not use sessions at all until everything works and then, if needed, turn sessions on for hotspots which are write-only, i.e. where you don't expect return values anyway.

**Comment by ijabz** [comment]
Originally I wasnt using sessions and it wasnt working then I started using sessions to see if that solved issue and then removed them again but the problems are still occurring. However I will retest and  repost a new stack trace making sure not using any sessions in a bit.

**Comment by ijabz** [comment]
Okay so simplified so not using sessions and doing nothing other than adding the files one at a time still getting errors, of 14 files tried to add all 14 were added to Music, but only 9 actually made it to my user playlist. One error reported by obsmusic, but two other tracks null was returned for Track object, foir two others there are no errors but not added to the playlist !

Don't know if I amdoing something fundamentally wrong but I can't think what, all tasks are called from the same class that runs continually on same thread, it picks up files as they are added to a queue and adds them to Music app

```
Application app = Application.getInstance();
            JaplScriptFile[] musicFiles = {new JaplScriptFile(Paths.get(filename))};
            track = app.add(musicFiles, userPlaylist);

            if(track!=null)
            {
                if(track.isInstanceOf(FileTrack.CLASS))
                {
                    fileTrack = track.cast(FileTrack.class);
                }
                else
                {
                    Errors.addError("New Track "+filename+ " not of type FileTrack");
                    MainWindow.logger.log(Level.WARNING, "New Track "+ filename + "not of type FileTrack");
                }
            }
            else
            {
                Errors.addError("New Track "+filename+ " not added to Music App");
                MainWindow.logger.log(Level.WARNING, "New Track "+ filename + " not added to Music App");
            }

```

06/04/2022 11.21.47:BST:FINE: Return value: «class cFlT» id 1461 of «class cUsP» id 1432 of «class cSrc» id 64
06/04/2022 11.21.47:BST:FINE: tell application "Music"
add  {(POSIX file ("/Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/03 - Funky Dory (single).wav"))} to «class cUsP» id 1432 of «class cSrc» id 64 
end tell
 == > «class cFlT» id 1461 of «class cUsP» id 1432 of «class cSrc» id 64
06/04/2022 11.21.47:BST:FINE: Script: tell application "Music"
return class of «class cFlT» id 1461 of «class cUsP» id 1432 of «class cSrc» id 64
end tell

06/04/2022 11.21.47:BST:Errors:addError:SEVERE: Adding Error:Unable to add new track /Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/03 - Funky Dory (single).wav to Music app because {
    NSAppleScriptErrorAppName = Music;
    NSAppleScriptErrorBriefMessage = "Can’t get class of file track id 1461 of user playlist id 1432 of source id 64.";
    NSAppleScriptErrorMessage = "Music got an error: Can’t get class of file track id 1461 of user playlist id 1432 of source id 64.";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {33, 5}";
}
java.lang.Exception
	at com.jthink.songkong.analyse.general.Errors.addError(Errors.java:28)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.addNewTrack(OSXUpdateMusicWithChanges.java:347)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.analyseFiles(OSXUpdateMusicWithChanges.java:173)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.updateItunes(OSXUpdateMusicWithChanges.java:217)
	at com.jthink.songkong.ituneshelper.UpdateItunesWithChanges.call(UpdateItunesWithChanges.java:156)
	at com.jthink.songkong.ituneshelper.UpdateItunesWithChanges.call(UpdateItunesWithChanges.java:33)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
06/04/2022 11.21.47:BST:OSXUpdateMusicWithChanges:addNewTrack:WARNING: Unable to add new track to Music App:{
    NSAppleScriptErrorAppName = Music;
    NSAppleScriptErrorBriefMessage = "Can’t get class of file track id 1461 of user playlist id 1432 of source id 64.";
    NSAppleScriptErrorMessage = "Music got an error: Can’t get class of file track id 1461 of user playlist id 1432 of source id 64.";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {33, 5}";
}
com.tagtraum.japlscript.execution.JaplScriptException: {
    NSAppleScriptErrorAppName = Music;
    NSAppleScriptErrorBriefMessage = "Can’t get class of file track id 1461 of user playlist id 1432 of source id 64.";
    NSAppleScriptErrorMessage = "Music got an error: Can’t get class of file track id 1461 of user playlist id 1432 of source id 64.";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {33, 5}";
}
	at com.tagtraum.japlscript.execution.CocoaScriptExecutor.execute(Native Method)
	at com.tagtraum.japlscript.execution.CocoaScriptExecutor.executeImpl(CocoaScriptExecutor.java:28)
	at com.tagtraum.japlscript.execution.ScriptExecutor.execute(ScriptExecutor.java:102)
	at com.tagtraum.japlscript.ObjectInvocationHandler.executeAppleScript(ObjectInvocationHandler.java:476)
	at com.tagtraum.japlscript.ObjectInvocationHandler.executeAppleScript(ObjectInvocationHandler.java:468)
	at com.tagtraum.japlscript.ObjectInvocationHandler.executeAppleScript(ObjectInvocationHandler.java:464)
	at com.tagtraum.japlscript.ObjectInvocationHandler.getTypeClass(ObjectInvocationHandler.java:119)
	at com.tagtraum.japlscript.language.ReferenceImpl.getTypeClass(ReferenceImpl.java:66)
	at com.tagtraum.japlscript.language.TypeClass.isInstance(TypeClass.java:204)
	at com.tagtraum.japlscript.ObjectInvocationHandler.invoke(ObjectInvocationHandler.java:180)
	at jdk.proxy2/jdk.proxy2.$Proxy66.isInstanceOf(Unknown Source)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.addNewTrack(OSXUpdateMusicWithChanges.java:276)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.analyseFiles(OSXUpdateMusicWithChanges.java:173)
	at com.jthink.songkong.ituneshelper.OSXUpdateMusicWithChanges.updateItunes(OSXUpdateMusicWithChanges.java:217)
	at com.jthink.songkong.ituneshelper.UpdateItunesWithChanges.call(UpdateItunesWithChanges.java:156)
	at com.jthink.songkong.ituneshelper.UpdateItunesWithChanges.call(UpdateItunesWithChanges.java:33)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
06/04/2022 11.21.47:BST:OSXUpdateMusicWithChanges:analyseFiles:WARNING: Track not found in Music app Database:/Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/04 - Fools.wav
06/04/2022 11.21.47:BST:FINE: Script: tell application "Music"
add  {(POSIX file ("/Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/04 - Fools.wav"))} to «class cUsP» id 1432 of «class cSrc» id 64 
end tell

06/04/2022 11.21.47:BST:FINE: Return value: «class cFlT» id 1475 of «class cUsP» id 1432 of «class cSrc» id 64
06/04/2022 11.21.47:BST:FINE: tell application "Music"
add  {(POSIX file ("/Users/paultaylor/Documents/Music/WAV_NAIM/PopRock/PopRock/PopRock/Rachel Stevens/Funky Dory/04 - Fools.wav"))} to «class cUsP» id 1432 of «class cSrc» id 64 
end tell
 == > «class cFlT» id 1475 of «class cUsP» id 1432 of «class cSrc» id 64
06/04/2022 11.21.47:BST:FINE: Script: tell application "Music"
return class of «class cFlT» id 1475 of «class cUsP» id 1432 of «class cSrc» id 64

**Comment by hendriks73** [comment]
I took a look at my own code for this scenario and found that I

- always add arrays of files (up to 100 at a time)
- have some comment in the code that talks about *not overwhelming iTunes*, whatever that means.

my guess is that Music/iTunes cannot handle your requests well/quick enough or processes the `add` asynchronously (but does not say so).

What happens when you add all 14 tracks at once?
What happens when you wait for a second after adding?

**Comment by ijabz** [comment]
Hi, yes I think it is hidden case of asynchrous processing !

I was testing this on a new mac m1 I haven't used much and I suddenly remembered the Music option, **Copy files to Music Media folder when adding to Library**, disabling this option fixed the issue.

Then I reenabled the option, but did Thread.sleep(5000) between each file add and that also worked.

So thanks, now my difficult is I don't want to delays things needlessely, and delay is going to depend on various factors that difficult to quantify> Maybe I should try and lookup the new track before continuing, havent worked out the best option for doing that yet.

I could also try batching up the tracks into one session, will take a bit rework because currently I just take single song of queu and process.

**Comment by ijabz** [comment]
Reduced to 1 second and worked first few times, bu then failed on one file
Modified to two seconds and has not failed yet.
Will try batching up requests into whole albums and running in one session ans see how that goes.

**Comment by hendriks73** [comment]
Since you are expecting return values from individual calls, using JaplScript Sessions may not be the best idea. Rather add multiple tracks at the same time using an array of `JaplScriptFile`s.

**Comment by ijabz** [comment]
Sorry that is what I meant

**Comment by ijabz** [comment]
Something I dont understand about the add method when adding multiple files from the api docs it only returns a reference to one track ?

**Comment by hendriks73** [comment]
That's unfortunately one of the instances, where the interface generation fails.

In the `.sdef` file that is used for generation, the return type is declared as "track", not list of tracks. That's why JaplScript generates `Track` as return type and not `Track[]`.

ObstMusic/ObstTunes work around this for some other commands (`convert()`) by simply replacing the Java sig after generation (see https://github.com/japlscript/obstmusic/blob/dev/src/main/japlscript/japlscript.xml#L23).

I have added `add()` to the list of *manual* replacements for both ObstMusic/ObstTunes in the `dev` branch.

**Comment by ijabz** [comment]
Actually i needed to update my Windows code (uses Jacob) to match shared interface and I find when I add new tracks there the add method is on the playlist itself and that returns an IITOperationStatus class, indicnating that it can take a while.
```
 IITOperationStatus opStatus = playlist.addFile(filename);
            while (opStatus.inProgress())
            {
                //Wait to complete
            }
```

Funny that the applescript version doesnt have the same thing

**Comment by ijabz** [comment]
Great but having slight problem with building this, git cloned the main branch and ran mvn install -DskipTests=true on MacOS worked fine. But my main dev machine is windows so I need to the new class on that machine so repeated this but got
```

japlscript:
    [mkdir] Created dir: c:\Code\jthink\obstmusic\target\generated-sources\main\java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.429 s
[INFO] Finished at: 2022-04-08T13:24:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project obstmusic: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] c:\Code\jthink\obstmusic\src\main\japlscript\japlscript.xml:7: java.lang.UnsupportedClassVersionError: com/tagtraum/japlscript/generation/GeneratorAntTask has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] around Ant part ...<ant antfile="c:\Code\jthink\obstmusic/src/main/japlscript/japlscript.xml" inheritRefs="true"/>... @ 5:98 in c:\Code\jthink\obstmusic\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

c:\Code\jthink\obstmusic>java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing) 

```

Not sure why the difference, class version 52 is Java 8 and class version is Java 9,  on both computers the installed Java version is 17.02 Temerion

**Comment by ijabz** [comment]
Ok the problem was i have JAVA_HOME set to a Java 8 install
Side not pointed it to a java 11 install and then failed on building Javadoc
Pointed to Java 17 and it worked

**Comment by ijabz** [comment]
Okay thanks, so that works better with adding the new files
Two points to note:
After the files are added if they are wav I then copy the metadata for each file to iTunes because it doesnt read metadata from wav. If I remove the delay then there are random errors at this stage, but if I add a  1second delay back in per song then okay, and that is better for me as I only have to do delay if wav which is quite rare.
I still support itunes so also had to make the change for obstunes as well
