### ISSUE TITLE
Global Playlist needs to reference as 0 to get as 1

### ISSUE THREAD

**Issue by ijabz** [hendriks73/obstmusic#2]
In applescript global playlist has index 1 but

`Playlist globalPlaylist = app.getPlaylist(1).getTracks();`

didn't work I had to do

`Playlist globalPlaylist = app.getPlaylist(0).getTracks();`

and when converted to applescript is converted to 

`return tracks of playlist 1`

Not clear why this is this the case ?

`

**Comment by hendriks73** [comment]
AppleScript does one-based indexing, Java indexing is zero-based.
JaplScript tries to hide the AppleScript side of things as much as possible, thus it converts between the two.

Clarified behavior in generated Javadocs: https://github.com/japlscript/japlscript/commit/4efcaf6ee8043ac8d840128e7d4e15f6d03de879

**Comment by ijabz** [comment]
Thought that would be the case, however the library is quite tightly bound to applescript (e.g the way you have to pass filters) so personally Im not sure changing the index really helps, but I guess personal choice.

**Comment by hendriks73** [comment]
> e.g the way you have to pass filters

You don't have to. But you can to not totally miss out on some better AppleScript features.
I my own code, I treat passing filters as a last resort to avoid a serious performance penalty.

> but I guess personal choice.

Yes.
