### ISSUE TITLE
Is there a way just to get Tracks of type FileTrack from the Global Playlist using a filter

### ISSUE THREAD

**Issue by ijabz** [hendriks73/obstmusic#3]
With a user playlist in can restrict the tracks returned to only those that represent an actual file
`
 FileTrack[] fileTracks = userPlaylist.getFileTracks();`

but getFileTracks() does not exist if using the global playlist, only getTracks()

`app.getPlaylist(1).getTracks()`

and I get that because it wont just contains FIleTracks, but that is all i am interested in so i guess i can filter using

`app.getPlaylist(1).getTracks(**filter**)`

but what do i set as the filter ?

**Comment by hendriks73** [comment]
I'd try `"class = file track"`, but really, this is an AppleScript issue not an ObstMusic issue, since the filter is passed verbatim to AppleScript.

**Comment by ijabz** [comment]
Didnt work, tried a few variations without any luck. If I get properties for a file track then javascript reports Klass=<<class FIT>> so that a clue but I assume Klass is a java thing 

You are right its an applescript issue and Ive raised a question on stackoverflow https://stackoverflow.com/questions/71784240/when-you-get-the-tracks-from-the-global-playlist-from-itunes-apple-music-with-app but I think the real strength of japlscript is making easier to write code to interface with Apple appliocations for those of us not very familiar with Applescript

**Comment by hendriks73** [comment]
> but I think the real strength of japlscript is making easier to write code to interface with Apple appliocations for those of us not very familiar with Applescript

That's totally the intention. However, some things are better and faster achieved with some AppleScript snippet. Hence the possibility to use these filters.

And yes, AppleScript is no fun at all and I like to avoid it.

For fast read-access to iTunes/Music, you might want to consider using https://github.com/hendriks73/jitlibrary instead of obstmusic.

**Comment by ijabz** [comment]
ah okay I think I was going to investigate jitl years back but then dismissed it because Apple Music came along and I thought it was only for iTunes!

May well investigate at later date, does it work for Intel and M1 chips ?

**Comment by hendriks73** [comment]
> does it work for Intel and M1 chips ?

Yes.

**Comment by ijabz** [comment]
ok this works (from stackoverflow)

`tell application "Music" to return file tracks of playlist 1`

but can than be done with obstmusic ?

**Comment by hendriks73** [comment]
Actually, if `userPlaylist` is really a `com.tagtraum.macos.music.UserPlaylist`, you can simply call [userPlaylist .getFileTracks()](https://japlscript.github.io/obstmusic/com/tagtraum/macos/music/UserPlaylist.html#getFileTracks--), since `file tracks` is a declared collection (in AppleScript-speak: "element") of every user playlist.

**Comment by ijabz** [comment]
userPlaylist is yes, but not the global playlist (playlist 1)

**Comment by hendriks73** [comment]
The `LibraryPlaylist` also declares a method called [getFileTracks()](https://japlscript.github.io/obstmusic/com/tagtraum/macos/music/LibraryPlaylist.html#getFileTracks--).

**Comment by hendriks73** [comment]
See also https://stackoverflow.com/a/71793875/942774

**Comment by ijabz** [comment]
Ah I didnt see LibraryPlaylist class, okay got it

```
Playlist globalPlaylist = app.getPlaylist(0);
FileTrack[] fileTracks  = globalPlaylist.cast(LibraryPlaylist.class).getFileTracks(); 
```
