### ISSUE TITLE
Non-idiomatic 'add' API

### ISSUE THREAD

**Issue by gravelld** [hendriks73/obstmusic#4]
In the [examples](https://github.com/japlscript/obstmusic#user-content-usage) there's some sample code to add artwork:

        // get the index of the artwork *after* the last artwork
        final int addIndex = currentTrack.countArtworks();
        // create a location specifier for the new artwork
        final Artwork newArtwork = currentTrack.getArtwork(addIndex);

This API design is not really idiomatic to a Java developer. Java APIs would tend to not allow the creation of an `Artwork` using a `get`ter. Instead, `addArtwork(Artwork)` would be preferable.

If this is because the code is generated and cannot be avoided, it might be preferable to have the original approach rather than _two_ approaches...

**Comment by hendriks73** [comment]
Fixed. Thanks for raising this issue! ;-)
